export const TEAM_MAP: Record<string, string> = {
  'Canadá': 'ca',
  'Marruecos': 'ma',
  'USA': 'us',
  'EEUU': 'us',
  'Australia': 'au',
  'España': 'es',
  'Italia': 'it',
  'Japón': 'jp',
  'México': 'mx',
  'Francia': 'fr',
  'Noruega': 'no',
  'Brasil': 'br',
  'Inglaterra': 'gb',
  'Argentina': 'ar',
  'Arabia Saudí': 'sa',
  'A. Saudí': 'sa',
  'Polonia': 'pl',
  'Dinamarca': 'dk',
  'Túnez': 'tn',
  'Gales': 'gb-wls',
  'Senegal': 'sn',
  'Qatar': 'qa',
  'Ecuador': 'ec',
  'Países Bajos': 'nl',
  'Suiza': 'ch',
  'Corea del Sur': 'kr',
  'Nigeria': 'ng',
  'Alemania': 'de',
  'Portugal': 'pt',
  'Uruguay': 'uy',
  'Colombia': 'co',
  'Nueva Zelanda': 'nz',
  'Arabia Saudita': 'sa',
  'Bélgica': 'be',
  'Croacia': 'hr',
  'Perú': 'pe',
  'Chile': 'cl',
  'Camerún': 'cm',
  'Egipto': 'eg',
  'Suecia': 'se',
  'Austria': 'at',
  'Jamaica': 'jm',
  'Turquía': 'tr',
  'Hungría': 'hu',
  'Panamá': 'pa',
  'Argelia': 'dz',
  'Costa de Marfil': 'ci',
  'Serbia': 'rs',
  'Gana': 'gh',
  'Ghana': 'gh',
  'Irán': 'ir',
  'Holanda': 'nl',
  'Escocia': 'gb-sct',
};

export const getFlagUrl = (teamName: string) => {
  const code = TEAM_MAP[teamName] || 'un';
  return `https://flagcdn.com/w80/${code.toLowerCase()}.png`;
};
