export interface ScorerCandidate {
  name: string;
  team: string;
  code: string;
  position: string;
  photoUrl: string;
  story: string;
  projection: string;
}

export const SCORER_CANDIDATES: ScorerCandidate[] = [
  {
    name: 'Kylian Mbappe',
    team: 'Francia',
    code: 'FRA',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Kylian%20Mbapp%C3%A9%202019.jpg',
    story: 'Bota de Oro 2022 y referencia ofensiva de Francia.',
    projection: 'Perfil top: penaltis, transiciones y volumen alto de remate.',
  },
  {
    name: 'Erling Haaland',
    team: 'Noruega',
    code: 'NOR',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Erling%20Haaland%202023.jpg',
    story: 'Debut mundialista esperado si Noruega confirma su plaza.',
    projection: 'Apuesta de techo enorme: área, balón parado y penaltis.',
  },
  {
    name: 'Lionel Messi',
    team: 'Argentina',
    code: 'ARG',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Lionel%20Messi%20WC2022.jpg',
    story: 'Campeón 2022 y máximo foco creativo de Argentina.',
    projection: 'Más asistente que antes, pero con penaltis y golpeo decisivo.',
  },
  {
    name: 'Harry Kane',
    team: 'Inglaterra',
    code: 'ENG',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Harry%20Kane%202018.jpg',
    story: 'Bota de Oro 2018 y lanzador principal de Inglaterra.',
    projection: 'Regularidad altísima: penaltis, remate y juego asociativo.',
  },
  {
    name: 'Vinicius Junior',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Vinicius%20Junior%202018.jpg',
    story: 'Desequilibrio principal de Brasil en campo abierto.',
    projection: 'Potencial alto si Brasil domina territorios y transiciones.',
  },
  {
    name: 'Jude Bellingham',
    team: 'Inglaterra',
    code: 'ENG',
    position: 'Centrocampista',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jude%20Bellingham%202022.jpg',
    story: 'Llegador diferencial, ya decisivo en grandes torneos.',
    projection: 'Opción premium desde segunda línea y balón parado.',
  },
  {
    name: 'Lamine Yamal',
    team: 'España',
    code: 'ESP',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Lamine%20Yamal%202023.jpg',
    story: 'Talento diferencial de España por derecha.',
    projection: 'Más generador que nueve, pero puede sumar en partidos abiertos.',
  },
  {
    name: 'Florian Wirtz',
    team: 'Alemania',
    code: 'GER',
    position: 'Centrocampista',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Florian%20Wirtz%202022.jpg',
    story: 'Organizador ofensivo con llegada y último pase.',
    projection: 'Rendimiento muy ligado al volumen ofensivo alemán.',
  },
  {
    name: 'Jamal Musiala',
    team: 'Alemania',
    code: 'GER',
    position: 'Centrocampista',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Jamal%20Musiala%202022.jpg',
    story: 'Especialista en recibir entre líneas y romper partidos.',
    projection: 'Buen valor si Alemania avanza varias rondas.',
  },
  {
    name: 'Bukayo Saka',
    team: 'Inglaterra',
    code: 'ENG',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bukayo%20Saka%202018.jpg',
    story: 'Extremo con gol, asistencia y peso en el ataque inglés.',
    projection: 'Muy fiable para sumar, especialmente en fase de grupos.',
  },
  {
    name: 'Raphinha',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Raphinha%202022.jpg',
    story: 'Extremo de producción alta y balón parado.',
    projection: 'Interesante si Brasil reparte goles entre varios atacantes.',
  },
  {
    name: 'Cristiano Ronaldo',
    team: 'Portugal',
    code: 'POR',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Cristiano%20Ronaldo%202018.jpg',
    story: 'Histórico goleador mundialista y lanzador de penaltis.',
    projection: 'Apuesta emocional con valor si mantiene rol titular.',
  },
  {
    name: 'Bruno Fernandes',
    team: 'Portugal',
    code: 'POR',
    position: 'Centrocampista',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Bruno%20Fernandes%202018.jpg',
    story: 'Motor ofensivo de Portugal, llega mucho al área.',
    projection: 'Gran opción alternativa por penaltis, asistencias y tiros.',
  },
  {
    name: 'Julian Alvarez',
    team: 'Argentina',
    code: 'ARG',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Julian%20Alvarez%202022.jpg',
    story: 'Goleador clave en el título de Argentina 2022.',
    projection: 'Valor alto si Argentina sostiene dos puntas o presión alta.',
  },
  {
    name: 'Christian Pulisic',
    team: 'Estados Unidos',
    code: 'USA',
    position: 'Delantero',
    photoUrl: 'https://commons.wikimedia.org/wiki/Special:FilePath/Christian%20Pulisic%202019.jpg',
    story: 'Líder ofensivo del anfitrión estadounidense.',
    projection: 'Buena apuesta diferencial por protagonismo y balón parado.',
  },
];
