export interface ScorerCandidate {
  name: string;
  team: string;
  code: string;
  position: string;
  photoUrl: string;
  story: string;
  projection: string;
}

export const SCORER_CANDIDATES: ScorerCandidate[] = [
  {
    name: 'Kylian Mbappé',
    team: 'Francia',
    code: 'FRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg/330px-Picture_with_Mbapp%C3%A9_%28cropped_and_rotated%29.jpg',
    story: 'Bota de Oro 2022 y capitán ofensivo de Francia.',
    projection: 'Candidato premium: penaltis, velocidad y mucho volumen de remate.',
  },
  {
    name: 'Harry Kane',
    team: 'Inglaterra',
    code: 'ENG',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Harry_Kane_on_October_10%2C_2023.jpg/330px-Harry_Kane_on_October_10%2C_2023.jpg',
    story: 'Bota de Oro 2018 y máximo goleador histórico de Inglaterra.',
    projection: 'Muy estable: penaltis, remate, juego aéreo y liderazgo total.',
  },
  {
    name: 'Erling Haaland',
    team: 'Noruega',
    code: 'NOR',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Erling_Haaland_June_2025.jpg/330px-Erling_Haaland_June_2025.jpg',
    story: 'Referencia absoluta de Noruega y especialista en área.',
    projection: 'Techo altísimo si Noruega compite: remate, potencia y penaltis.',
  },
  {
    name: 'Lamine Yamal',
    team: 'España',
    code: 'ESP',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Lamine_Yamal_in_2025.jpg/330px-Lamine_Yamal_in_2025.jpg',
    story: 'Talento diferencial de España desde banda derecha.',
    projection: 'Más generador que nueve, pero con gol en partidos abiertos.',
  },
  {
    name: 'Vinícius Júnior',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg/330px-2023_05_06_Final_de_la_Copa_del_Rey_-_52879242230_%28cropped%29.jpg',
    story: 'Desequilibrio principal de Brasil en campo abierto.',
    projection: 'Gran valor si Brasil corre y juega muchos minutos en ventaja.',
  },
  {
    name: 'Julián Álvarez',
    team: 'Argentina',
    code: 'ARG',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/0/03/Argentina_national_football_team_-_2_-_2022_%28Juli%C3%A1n_%C3%81lvarez%29.jpg',
    story: 'Goleador clave en el título mundial de Argentina 2022.',
    projection: 'Apuesta muy seria si Argentina presiona alto y juega con dos puntas.',
  },
  {
    name: 'Mikel Oyarzabal',
    team: 'España',
    code: 'ESP',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f1/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_108_%28cropped%29.jpg/330px-UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_108_%28cropped%29.jpg',
    story: 'Delantero versátil y fiable en momentos de máxima presión.',
    projection: 'Interesante por eficacia, penaltis potenciales y lectura de área.',
  },
  {
    name: 'Lionel Messi',
    team: 'Argentina',
    code: 'ARG',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg/330px-Lionel_Messi_White_House_2026_%283x4_cropped%29.jpg',
    story: 'Campeón 2022 y figura histórica de Argentina.',
    projection: 'Más director que velocista, pero con penaltis y golpeo decisivo.',
  },
  {
    name: 'Cristiano Ronaldo',
    team: 'Portugal',
    code: 'POR',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg/330px-President_Donald_Trump_meets_with_Cristiano_Ronaldo_in_the_Oval_Office_%2854933344262%29_%28cropped_and_rotated%29.jpg',
    story: 'Goleador histórico de Portugal y de grandes torneos.',
    projection: 'Apuesta de experiencia: área, penaltis y colmillo competitivo.',
  },
  {
    name: 'Ousmane Dembélé',
    team: 'Francia',
    code: 'FRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Ousmane_Demb%C3%A9l%C3%A9_2018_%28cropped%29.jpg/330px-Ousmane_Demb%C3%A9l%C3%A9_2018_%28cropped%29.jpg',
    story: 'Atacante ambidiestro, vertical y campeón del mundo con Francia.',
    projection: 'Diferencial si Francia abre partidos y reparte goles entre extremos.',
  },
  {
    name: 'Raphinha',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/c/c6/RaphinhaBenfica_%28cropped%29.png',
    story: 'Extremo de producción alta y balón parado con Brasil.',
    projection: 'Muy útil si Brasil carga juego por bandas y suma faltas/penaltis.',
  },
  {
    name: 'Lautaro Martínez',
    team: 'Argentina',
    code: 'ARG',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Lautaro_Martinez_ARGENTINA_VS_VENEZUELA_2017.jpg/330px-Lautaro_Martinez_ARGENTINA_VS_VENEZUELA_2017.jpg',
    story: 'Nueve de área, campeón del mundo y recurso clave de Argentina.',
    projection: 'Buen valor si Argentina domina partidos y genera centros laterales.',
  },
  {
    name: 'Luis Díaz',
    team: 'Colombia',
    code: 'COL',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg/330px-FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_40_%28Luiz_D%C3%ADaz%29.jpg',
    story: 'Líder ofensivo colombiano por desborde, presión y remate.',
    projection: 'Apuesta diferencial si Colombia avanza y encuentra transiciones.',
  },
  {
    name: 'Viktor Gyökeres',
    team: 'Suecia',
    code: 'SWE',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Viktor_Gy%C3%B6keres_2018.jpg/330px-Viktor_Gy%C3%B6keres_2018.jpg',
    story: 'Nueve poderoso, directo y con gran producción goleadora reciente.',
    projection: 'Apuesta de impacto: rupturas, cuerpo a cuerpo y penalti probable.',
  },
  {
    name: 'Bukayo Saka',
    team: 'Inglaterra',
    code: 'ENG',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/1_bukayo_saka_arsenal_2025_%28cropped%29.jpg/330px-1_bukayo_saka_arsenal_2025_%28cropped%29.jpg',
    story: 'Extremo clave de Inglaterra, fiable en gol y asistencia.',
    projection: 'Perfil muy regular para sumar en fase de grupos y cruces.',
  },
  {
    name: 'Michael Olise',
    team: 'Francia',
    code: 'FRA',
    position: 'Centrocampista',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_10.jpg/330px-FC_RB_Salzburg_gegen_FC_Bayern_M%C3%BCnchen_%282026-01-06_Testspiel%29_10.jpg',
    story: 'Talento creativo de Francia entre banda y mediapunta.',
    projection: 'Buena apuesta alternativa si gana peso en balón parado y último pase.',
  },
  {
    name: 'Darwin Núñez',
    team: 'Uruguay',
    code: 'URU',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Darwin_N%C3%BA%C3%B1ez_%28cropped%29.jpg/330px-Darwin_N%C3%BA%C3%B1ez_%28cropped%29.jpg',
    story: 'Nueve de rupturas, potencia y volumen de ocasiones con Uruguay.',
    projection: 'Puede explotar si Uruguay juega vertical y roba cerca del área.',
  },
  {
    name: 'João Pedro',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/1d/Jo%C3%A3o_Pedro%2C_2025_FIFA_Club_World_Cup_final_%2854654843615%29.jpg',
    story: 'Delantero móvil, con recursos para jugar entre líneas y atacar área.',
    projection: 'Opción de cuota alta si Brasil le da minutos importantes.',
  },
  {
    name: 'Jude Bellingham',
    team: 'Inglaterra',
    code: 'ENG',
    position: 'Centrocampista',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg/330px-25th_Laureus_World_Sports_Awards_-_Red_Carpet_-_Jude_Bellingham_-_240422_190551-2_%28cropped%29.jpg',
    story: 'Llegador diferencial, con peso ofensivo en Inglaterra.',
    projection: 'Premium desde segunda línea: llegada, balón parado y jerarquía.',
  },
  {
    name: 'Endrick',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a1/Endrick-Palmeiras-Liverpool-abr24.jpg/330px-Endrick-Palmeiras-Liverpool-abr24.jpg',
    story: 'Delantero joven de Brasil, ya goleador en escenarios grandes.',
    projection: 'Apuesta explosiva si tiene minutos de revulsivo en partidos abiertos.',
  },
  {
    name: 'Arda Güler',
    team: 'Turquía',
    code: 'TUR',
    position: 'Centrocampista',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/2/26/Derbide_Fenerbah%C3%A7e_Yedek_Oyuncu_Arda_G%C3%BCler_%282021-22_S%C3%BCper_Lig_-_Cropped%29.jpg',
    story: 'Mediapunta zurdo, con golpeo y mucha libertad creativa.',
    projection: 'Valor diferencial por tiros lejanos, faltas y último pase.',
  },
  {
    name: 'Rayan Cherki',
    team: 'Francia',
    code: 'FRA',
    position: 'Centrocampista',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Cherki_asse_ol_2425.png/330px-Cherki_asse_ol_2425.png',
    story: 'Mediapunta creativo de Francia, capaz de cambiar ritmo y partido.',
    projection: 'Apuesta atrevida: menos segura, pero con mucho talento en pocos toques.',
  },
  {
    name: 'Alexander Isak',
    team: 'Suecia',
    code: 'SWE',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Alexander_Isak_56_%28cropped%29.jpg/330px-UEFA_EURO_qualifiers_Sweden_vs_Spain_20191015_Alexander_Isak_56_%28cropped%29.jpg',
    story: 'Delantero elegante, rápido y con definición de primer nivel.',
    projection: 'Gran pareja de techo alto con Suecia si el equipo pisa área.',
  },
  {
    name: 'Gonçalo Ramos',
    team: 'Portugal',
    code: 'POR',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Gon%C3%A7alo_Ramos_USMNT_v_Portugal_Mar_31_2026-32_%28cropped%29.jpg/250px-Gon%C3%A7alo_Ramos_USMNT_v_Portugal_Mar_31_2026-32_%28cropped%29.jpg',
    story: 'Nueve de Portugal, recordado por su hat-trick mundialista de 2022.',
    projection: 'Muy peligroso si Portugal le activa en el área y reparte minutos.',
  },
  {
    name: 'Richarlison',
    team: 'Brasil',
    code: 'BRA',
    position: 'Delantero',
    photoUrl: 'https://upload.wikimedia.org/wikipedia/commons/3/3d/Richarlison_%C3%A9_homenageado_na_ALES_%2810.July.2019%29_01_%28cropped%29.jpg',
    story: 'Delantero brasileño con historial de goles importantes en Mundial.',
    projection: 'Apuesta de área si Brasil necesita remate, agresividad y juego directo.',
  },
];
